ODATA 1421 - Add UpdateMethod to UpdateRestrictionsType
oasis-tcs/odata-vocabularies pull request #105
Opened 2021-03-03 17:53 UTC by mikepizzo

Preliminary update adds new property and enum to XML.

Does not yet add to JSON or .md.

2021-03-03 18:29 UTC, ralfhandl approved these changes

2021-03-04 17:45 UTC, HeikoTheissen requested changes

2021-03-04 17:45 UTC, HeikoTheissen commented on vocabularies/Org.OData.Capabilities.V1.xml
> +          <Annotation Term="Core.Description" String="The HTTP OPTIONS Method" />
```suggestion
          <Annotation Term="Core.Description" String="The HTTP HEAD Method" />

```

2021-03-04 17:51 UTC, HeikoTheissen approved these changes

2021-03-04 17:52 UTC, merged