Fixed description of SearchExpressions value "none"
oasis-tcs/odata-vocabularies pull request #133
Opened 2021-06-30 07:54 UTC by ralfhandl

Fixes https://issues.oasis-open.org/browse/ODATA-1453

2021-06-30 08:02 UTC, HeikoTheissen reviewed
So 0 has the same meaning as 7 (= 1 + 2 + 4)?

2021-06-30 08:10 UTC, ralfhandl commented
> So 0 has the same meaning as 7 (= 1 + 2 + 4)?

`UnsupportedExpressions: 0` means "you can use all expressions"

`UnsupportedExpressions: 7` means "you can't use AND, OR, and NOT"

2021-06-30 08:14 UTC, HeikoTheissen requested changes
Let others avoid the misunderstanding I suffered.

2021-06-30 08:14 UTC, HeikoTheissen commented on vocabularies/Org.OData.Capabilities.V1.xml
>            <Annotation Term="Core.Description" String="Multiple search terms separated by `AND`" />
```suggestion
          <Annotation Term="Core.Description" String="Multiple search terms separated by `AND` are not supported" />
```
and likewise for values 2 and 4.

2021-06-30 08:57 UTC, HeikoTheissen requested changes

2021-06-30 08:57 UTC, HeikoTheissen commented on vocabularies/Org.OData.Capabilities.V1.xml
> +          <Annotation Term="Core.Description" String="Precedence grouping of search expressions with parentheses are not supported" />
```suggestion
          <Annotation Term="Core.Description" String="Precedence grouping of search expressions with parentheses is not supported" />
```

2021-06-30 09:33 UTC, HeikoTheissen approved these changes

2023-01-10 14:50 UTC, HeikoTheissen approved these changes

2024-06-06 07:52 UTC, closed without merging